version: "1"
rules:
  - base: main
    upstream: preactjs:main
    mergeMethod: merge
    mergeUnstable: true
  - base: v10.x
    upstream: preactjs:v10.x
    mergeMethod: merge
    mergeUnstable: true
